FROM node:22

WORKDIR /app

# Install Redis
RUN apt-get update && \
    apt-get install -y redis-server && \
    rm -rf /var/lib/apt/lists/*

# Copy project
COPY . .

# Install dependencies
RUN npm install

# Build TypeScript (if applicable)
RUN npm run build

# Start Node
CMD ["npm", "run", "start"]